// category.js

const categories = [
  "CARDIOLOGY",
  "DERMATOLOGY",
  "ENDOCRINOLOGY",
  "GASTROENTEROLOGY",
  "GYNECOLOGY",
  "HEMATOLOGY",
  "INFECTIOUS_DISEASE",
  "NEPHROLOGY",
  "NEUROLOGY",
  "OBSTETRICS",
  "ONCOLOGY",
  "OPHTHALMOLOGY",
  "ORTHOPEDICS",
  "OTOLARYNGOLOGY",
  "PEDIATRICS",
  "PSYCHIATRY",
  "PULMONOLOGY",
  "RHEUMATOLOGY",
  "THERAPY",
  "UROLOGY",
  "PHYSIOLOGY",
];
export { categories };
